"""add client deactivation reason and client audit relation

Revision ID: 16fbab9ed93f
Revises: eb9a5f0ca9e3
Create Date: 2026-07-08 20:28:46.911653

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '16fbab9ed93f'
down_revision = 'eb9a5f0ca9e3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bitacora_auditoria', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cliente_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'clientes', ['cliente_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('clientes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('razon_desactivacion', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clientes', schema=None) as batch_op:
        batch_op.drop_column('razon_desactivacion')

    with op.batch_alter_table('bitacora_auditoria', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('cliente_id')

    # ### end Alembic commands ###
