"""remove_fecha_audiencia_from_expediente

Revision ID: 31aa40d60215
Revises: bc732920df5c
Create Date: 2026-07-15 19:06:56.328945

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '31aa40d60215'
down_revision = 'bc732920df5c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('alertas_plazos_audiencias', schema=None) as batch_op:
        batch_op.add_column(sa.Column('es_audiencia', sa.Boolean(), nullable=False))

    with op.batch_alter_table('expedientes_judiciales', schema=None) as batch_op:
        batch_op.drop_column('hora_audiencia')
        batch_op.drop_column('fecha_audiencia')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('expedientes_judiciales', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fecha_audiencia', sa.DATE(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('hora_audiencia', postgresql.TIME(), autoincrement=False, nullable=True))

    with op.batch_alter_table('alertas_plazos_audiencias', schema=None) as batch_op:
        batch_op.drop_column('es_audiencia')

    # ### end Alembic commands ###
