"""Add cliente_id to Documento

Revision ID: 322aff5ff18d
Revises: df1b11be1d82
Create Date: 2026-07-09 02:27:18.602848

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '322aff5ff18d'
down_revision = 'df1b11be1d82'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('documentos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cliente_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'clientes', ['cliente_id'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('documentos', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('cliente_id')

    # ### end Alembic commands ###
