"""add_tarea_asignados_relation

Revision ID: 44f839aa0701
Revises: df280d437929
Create Date: 2026-07-28 11:38:18.095990

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '44f839aa0701'
down_revision = 'df280d437929'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tarea_asignados',
    sa.Column('tarea_id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['tarea_id'], ['tareas.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('tarea_id', 'usuario_id')
    )
    # ### end Alembic commands ###
    
    # Copiar datos históricos de asignado_a_id a la nueva tabla tarea_asignados
    op.execute("""
        INSERT INTO tarea_asignados (tarea_id, usuario_id)
        SELECT id, asignado_a_id FROM tareas
        WHERE asignado_a_id IS NOT NULL
        ON CONFLICT DO NOTHING
    """)


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tarea_asignados')
    # ### end Alembic commands ###
