"""add_catalogs_and_dynamic_fields

Revision ID: 4a256ecec8c1
Revises: cae851fe6c86
Create Date: 2026-07-27 22:43:41.860047

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '4a256ecec8c1'
down_revision = 'cae851fe6c86'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('materias_legales',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('tipo_expediente', sa.String(length=50), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('procedimientos_legales',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('materia_id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=150), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('orden', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['materia_id'], ['materias_legales.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    
    # ------------------
    # SEED DATA
    # ------------------
    materia_table = sa.table('materias_legales',
        sa.column('id', sa.Integer),
        sa.column('nombre', sa.String),
        sa.column('tipo_expediente', sa.String),
        sa.column('activo', sa.Boolean),
        sa.column('descripcion', sa.Text)
    )
    
    materias_data = [
        {"id": 1, "nombre": "Civil", "tipo_expediente": "Judicial", "activo": True, "descripcion": "Materia Civil"},
        {"id": 2, "nombre": "Familia", "tipo_expediente": "Judicial", "activo": True, "descripcion": "Materia de Familia"},
        {"id": 3, "nombre": "Penal", "tipo_expediente": "Judicial", "activo": True, "descripcion": "Materia Penal"},
        {"id": 4, "nombre": "Laboral", "tipo_expediente": "Judicial", "activo": True, "descripcion": "Materia Laboral"},
        {"id": 5, "nombre": "Comercial", "tipo_expediente": "Judicial", "activo": True, "descripcion": "Materia Comercial"},
        {"id": 6, "nombre": "Inmobiliario", "tipo_expediente": "Judicial", "activo": True, "descripcion": "Materia Inmobiliaria"},
        {"id": 7, "nombre": "Tributario", "tipo_expediente": "Judicial", "activo": True, "descripcion": "Materia Tributaria / Impuestos (Litigio)"},
        {"id": 8, "nombre": "Migratorio", "tipo_expediente": "Administrativo", "activo": True, "descripcion": "Trámites Migratorios / DGM"},
        {"id": 9, "nombre": "ONAPI", "tipo_expediente": "Administrativo", "activo": True, "descripcion": "Propiedad Intelectual (ONAPI)"},
        {"id": 10, "nombre": "DGII", "tipo_expediente": "Administrativo", "activo": True, "descripcion": "Trámites Tributarios Administrativos (DGII)"},
        {"id": 11, "nombre": "Registro Mercantil", "tipo_expediente": "Administrativo", "activo": True, "descripcion": "Registro Mercantil / Cámaras de Comercio"},
        {"id": 12, "nombre": "JCE", "tipo_expediente": "Administrativo", "activo": True, "descripcion": "Junta Central Electoral"},
        {"id": 13, "nombre": "Ministerio de Trabajo", "tipo_expediente": "Administrativo", "activo": True, "descripcion": "Ministerio de Trabajo"},
        {"id": 14, "nombre": "Ayuntamientos", "tipo_expediente": "Administrativo", "activo": True, "descripcion": "Gestiones Municipales / Ayuntamientos"}
    ]
    op.bulk_insert(materia_table, materias_data)

    procedimiento_table = sa.table('procedimientos_legales',
        sa.column('id', sa.Integer),
        sa.column('materia_id', sa.Integer),
        sa.column('nombre', sa.String),
        sa.column('activo', sa.Boolean),
        sa.column('descripcion', sa.Text),
        sa.column('orden', sa.Integer)
    )
    
    procs_data = []
    pid = 1
    
    # Civil
    civil_procs = ["Cobro de Pesos", "Desalojo", "Daños y Perjuicios", "Partición", "Nulidad de Contrato", 
                   "Embargo Ejecutivo", "Embargo Retentivo", "Embargo Inmobiliario", "Ejecución de Sentencia", 
                   "Interdicto", "Responsabilidad Civil"]
    for idx, p in enumerate(civil_procs):
        procs_data.append({"id": pid, "materia_id": 1, "nombre": p, "activo": True, "descripcion": f"Procedimiento de {p}", "orden": idx})
        pid += 1

    # Familia
    familia_procs = ["Divorcio por Mutuo Consentimiento", "Divorcio por Incompatibilidad", "Pensión Alimentaria", 
                     "Aumento de Pensión", "Reducción de Pensión", "Custodia", "Guarda y Cuidado", "Régimen de Visitas", 
                     "Reconocimiento de Paternidad", "Impugnación de Paternidad", "Adopción", "Autorización de Viaje para Menores", 
                     "Liquidación de Bienes", "Tutela", "Curatela"]
    for idx, p in enumerate(familia_procs):
        procs_data.append({"id": pid, "materia_id": 2, "nombre": p, "activo": True, "descripcion": f"Procedimiento de {p}", "orden": idx})
        pid += 1

    # Penal
    penal_procs = ["Querella", "Denuncia", "Medida de Coerción", "Solicitud de Libertad", "Apelación", "Casación", 
                   "Revisión Penal", "Constitución en Actor Civil"]
    for idx, p in enumerate(penal_procs):
        procs_data.append({"id": pid, "materia_id": 3, "nombre": p, "activo": True, "descripcion": f"Procedimiento de {p}", "orden": idx})
        pid += 1

    # Laboral
    laboral_procs = ["Despido Injustificado", "Dimisión", "Prestaciones Laborales", "Accidente de Trabajo", 
                     "Reclamación Salarial", "Reintegro", "Conflicto Colectivo"]
    for idx, p in enumerate(laboral_procs):
        procs_data.append({"id": pid, "materia_id": 4, "nombre": p, "activo": True, "descripcion": f"Procedimiento de {p}", "orden": idx})
        pid += 1

    # Comercial
    comercial_procs = ["Incumplimiento Contractual", "Cobro Comercial", "Constitución de Empresa", "Disolución", 
                       "Modificación Estatutaria", "Fusión", "Liquidación"]
    for idx, p in enumerate(comercial_procs):
        procs_data.append({"id": pid, "materia_id": 5, "nombre": p, "activo": True, "descripcion": f"Procedimiento de {p}", "orden": idx})
        pid += 1

    # Inmobiliario
    inmob_procs = ["Deslinde", "Saneamiento", "Transferencia", "Hipoteca", "Cancelación de Hipoteca", 
                   "Litis sobre Derechos Registrados", "Mensura", "Condominios"]
    for idx, p in enumerate(inmob_procs):
        procs_data.append({"id": pid, "materia_id": 6, "nombre": p, "activo": True, "descripcion": f"Procedimiento de {p}", "orden": idx})
        pid += 1

    # Tributario
    trib_procs = ["Recurso Tributario", "Impugnación", "Fiscalización", "Cobro Tributario", "Exenciones", "Consultoría Fiscal"]
    for idx, p in enumerate(trib_procs):
        procs_data.append({"id": pid, "materia_id": 7, "nombre": p, "activo": True, "descripcion": f"Procedimiento de {p}", "orden": idx})
        pid += 1

    # Migratorio
    migra_procs = ["Visa", "Residencia Temporal", "Residencia Permanente", "Renovación", "Cambio de Categoría", 
                   "Naturalización", "Ciudadanía", "Permiso de Trabajo", "Pasaporte", "Carta de Ruta"]
    for idx, p in enumerate(migra_procs):
        procs_data.append({"id": pid, "materia_id": 8, "nombre": p, "activo": True, "descripcion": f"Procedimiento de {p}", "orden": idx})
        pid += 1

    # ONAPI
    onapi_procs = ["Registro de Marca", "Renovación de Marca", "Nombre Comercial", "Patente", "Diseño Industrial", 
                   "Oposición", "Cesión"]
    for idx, p in enumerate(onapi_procs):
        procs_data.append({"id": pid, "materia_id": 9, "nombre": p, "activo": True, "descripcion": f"Procedimiento de {p}", "orden": idx})
        pid += 1

    # DGII
    dgii_procs = ["Inscripción RNC", "Actualización RNC", "Comprobantes Fiscales", "Declaraciones", "Recursos", "Exenciones"]
    for idx, p in enumerate(dgii_procs):
        procs_data.append({"id": pid, "materia_id": 10, "nombre": p, "activo": True, "descripcion": f"Procedimiento de {p}", "orden": idx})
        pid += 1

    # Registro Mercantil
    reg_merc_procs = ["Constitución Sociedad", "Renovación Registro", "Transformación", "Disolución", "Cambio de Nombre Comercial"]
    for idx, p in enumerate(reg_merc_procs):
        procs_data.append({"id": pid, "materia_id": 11, "nombre": p, "activo": True, "descripcion": f"Procedimiento de {p}", "orden": idx})
        pid += 1

    op.bulk_insert(procedimiento_table, procs_data)

    with op.batch_alter_table('expedientes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('materia_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('procedimiento_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('prioridad', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('nivel_riesgo', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('probabilidad_exito', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('origen_cliente', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('fecha_contratacion', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('valor_estimado_caso', sa.Numeric(precision=18, scale=2), nullable=True))
        batch_op.add_column(sa.Column('datos_dinamicos', sa.JSON(), nullable=True))
        batch_op.create_foreign_key(None, 'procedimientos_legales', ['procedimiento_id'], ['id'], ondelete='RESTRICT')
        batch_op.create_foreign_key(None, 'materias_legales', ['materia_id'], ['id'], ondelete='RESTRICT')

    # ------------------
    # DATA MIGRATION FOR HISTORICAL RECORDS
    # ------------------
    # 1. Map Materia Legal based on old text columns
    op.execute("""
        UPDATE expedientes 
        SET materia_id = m.id 
        FROM materias_legales m, expedientes_judiciales ej
        WHERE ej.id = expedientes.id
          AND LOWER(trim(ej.rama_derecho)) = LOWER(trim(m.nombre)) 
          AND m.tipo_expediente = 'Judicial';
    """)
    op.execute("""
        UPDATE expedientes 
        SET materia_id = m.id 
        FROM materias_legales m, expedientes_administrativos ea
        WHERE ea.id = expedientes.id
          AND LOWER(trim(ea.tipo_proceso)) = LOWER(trim(m.nombre)) 
          AND m.tipo_expediente = 'Administrativo';
    """)
    
    # 2. Fallbacks for other known variations
    op.execute("""
        UPDATE expedientes 
        SET materia_id = (SELECT id FROM materias_legales WHERE nombre = 'ONAPI' LIMIT 1)
        FROM expedientes_administrativos ea
        WHERE ea.id = expedientes.id AND expedientes.materia_id IS NULL AND LOWER(ea.tipo_proceso) LIKE '%propiedad%';
    """)
    op.execute("""
        UPDATE expedientes 
        SET materia_id = (SELECT id FROM materias_legales WHERE nombre = 'Migratorio' LIMIT 1)
        FROM expedientes_administrativos ea
        WHERE ea.id = expedientes.id AND expedientes.materia_id IS NULL AND LOWER(ea.tipo_proceso) LIKE '%migra%';
    """)
    op.execute("""
        UPDATE expedientes 
        SET materia_id = (SELECT id FROM materias_legales WHERE nombre = 'Registro Mercantil' LIMIT 1)
        FROM expedientes_administrativos ea
        WHERE ea.id = expedientes.id AND expedientes.materia_id IS NULL AND LOWER(ea.tipo_proceso) LIKE '%corpora%';
    """)

    # 3. Map Procedimiento based on sub_categoria (Judicial) or sub_proceso (Administrativo)
    op.execute("""
        UPDATE expedientes 
        SET procedimiento_id = p.id 
        FROM procedimientos_legales p, expedientes_judiciales ej
        WHERE ej.id = expedientes.id
          AND (LOWER(trim(ej.sub_categoria)) = LOWER(trim(p.nombre)) OR LOWER(trim(ej.tipo_accion)) = LOWER(trim(p.nombre))) 
          AND p.materia_id = expedientes.materia_id;
    """)
    op.execute("""
        UPDATE expedientes 
        SET procedimiento_id = p.id 
        FROM procedimientos_legales p, expedientes_administrativos ea
        WHERE ea.id = expedientes.id
          AND LOWER(trim(ea.sub_proceso)) = LOWER(trim(p.nombre)) 
          AND p.materia_id = expedientes.materia_id;
    """)

    # 4. Fallbacks for procedure variations
    op.execute("""
        UPDATE expedientes 
        SET procedimiento_id = (SELECT id FROM procedimientos_legales WHERE nombre = 'Residencia Temporal' LIMIT 1)
        FROM expedientes_administrativos ea
        WHERE ea.id = expedientes.id AND expedientes.procedimiento_id IS NULL AND LOWER(ea.sub_proceso) LIKE '%residencia%';
    """)
    op.execute("""
        UPDATE expedientes 
        SET procedimiento_id = (SELECT id FROM procedimientos_legales WHERE nombre = 'Registro de Marca' LIMIT 1)
        FROM expedientes_administrativos ea
        WHERE ea.id = expedientes.id AND expedientes.procedimiento_id IS NULL AND LOWER(ea.sub_proceso) LIKE '%marca%';
    """)
    op.execute("""
        UPDATE expedientes 
        SET procedimiento_id = (SELECT id FROM procedimientos_legales WHERE nombre = 'Constitución Sociedad' LIMIT 1)
        FROM expedientes_administrativos ea
        WHERE ea.id = expedientes.id AND expedientes.procedimiento_id IS NULL AND LOWER(ea.sub_proceso) LIKE '%constitu%';
    """)

    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.alter_column('bloqueado_hasta',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.alter_column('bloqueado_hasta',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)

    with op.batch_alter_table('expedientes', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('datos_dinamicos')
        batch_op.drop_column('valor_estimado_caso')
        batch_op.drop_column('fecha_contratacion')
        batch_op.drop_column('origen_cliente')
        batch_op.drop_column('probabilidad_exito')
        batch_op.drop_column('nivel_riesgo')
        batch_op.drop_column('prioridad')
        batch_op.drop_column('procedimiento_id')
        batch_op.drop_column('materia_id')

    op.drop_table('procedimientos_legales')
    op.drop_table('materias_legales')
    # ### end Alembic commands ###
