"""refactor: implementar herencia de tablas polimorficas para expedientes

Revision ID: 5c14fe94c45e
Revises: 670a960edca3
Create Date: 2026-06-30 19:50:08.757575

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5c14fe94c45e'
down_revision = '670a960edca3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('expedientes_administrativos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tipo_proceso', sa.String(length=100), nullable=True),
    sa.Column('sub_proceso', sa.String(length=100), nullable=True),
    sa.Column('institucion_encargada', sa.String(length=150), nullable=True),
    sa.Column('descripcion_tramite', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['expedientes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('expedientes_judiciales',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rama_derecho', sa.String(length=100), nullable=True),
    sa.Column('sub_categoria', sa.String(length=100), nullable=True),
    sa.Column('tipo_accion', sa.String(length=100), nullable=True),
    sa.Column('numero_expediente_tribunal', sa.String(length=100), nullable=True),
    sa.Column('tribunal_asignado', sa.String(length=150), nullable=True),
    sa.Column('juez_asignado', sa.String(length=150), nullable=True),
    sa.Column('fecha_audiencia', sa.Date(), nullable=True),
    sa.Column('hora_audiencia', sa.Time(), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['expedientes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('requisitos_administrativos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('expediente_id', sa.Integer(), nullable=False),
    sa.Column('descripcion', sa.String(length=255), nullable=False),
    sa.Column('estado', sa.String(length=50), nullable=False),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(timezone=True), nullable=True),
    sa.Column('fecha_completado', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['expediente_id'], ['expedientes_administrativos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('requisitos_administrativos')
    op.drop_table('expedientes_judiciales')
    op.drop_table('expedientes_administrativos')
    # ### end Alembic commands ###
