"""ampliar tabla clientes

Revision ID: 670a960edca3
Revises: bbe567fa86a7
Create Date: 2026-06-25 20:53:33.317901

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '670a960edca3'
down_revision = 'bbe567fa86a7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clientes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tipo_cliente', sa.String(length=50), server_default='Persona física', nullable=False))
        batch_op.add_column(sa.Column('fecha_nacimiento', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('direccion', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clientes', schema=None) as batch_op:
        batch_op.drop_column('direccion')
        batch_op.drop_column('fecha_nacimiento')
        batch_op.drop_column('tipo_cliente')

    # ### end Alembic commands ###
