"""add login lockout columns

Revision ID: 75cadc9c150a
Revises: 5f459bcd028b
Create Date: 2026-07-18 11:23:33.066074

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '75cadc9c150a'
down_revision = '5f459bcd028b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('intentos_fallidos', sa.Integer(), nullable=False, server_default=sa.text('0')))
        batch_op.add_column(sa.Column('bloqueado_hasta', sa.DateTime(timezone=True), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.drop_column('bloqueado_hasta')
        batch_op.drop_column('intentos_fallidos')

    # ### end Alembic commands ###
