"""add_billing_and_contracts_module

Revision ID: 793927c103c1
Revises: 8fc5d1f84bca
Create Date: 2026-07-27 23:42:44.809613

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '793927c103c1'
down_revision = '8fc5d1f84bca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('presupuestos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=150), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('materia', sa.String(length=50), nullable=False),
    sa.Column('tipo_asunto', sa.String(length=100), nullable=False),
    sa.Column('monto_subtotal', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('monto_itbis', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('monto_total', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('fecha_emision', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('detalles_presupuestos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('presupuesto_id', sa.Integer(), nullable=False),
    sa.Column('descripcion', sa.String(length=255), nullable=False),
    sa.Column('cantidad', sa.Integer(), nullable=False),
    sa.Column('precio_unitario', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('subtotal', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['presupuesto_id'], ['presupuestos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('expedientes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('esquema_cobro', sa.String(length=30), nullable=True, server_default='Fijo'))
        batch_op.add_column(sa.Column('tarifa_monto', sa.Numeric(precision=18, scale=2), nullable=True, server_default='0.00'))
        batch_op.add_column(sa.Column('porcentaje_exito', sa.Numeric(precision=5, scale=2), nullable=True, server_default='0.00'))
    op.create_table('parametros_fiscales',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('clave', sa.String(length=50), nullable=False),
    sa.Column('valor', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('descripcion', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('clave')
    )
    op.create_table('recibos_internos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('numero_recibo', sa.String(length=20), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('fecha_emision', sa.DateTime(timezone=True), nullable=False),
    sa.Column('monto_total', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('numero_recibo')
    )
    op.create_table('contratos_honorarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('expediente_id', sa.Integer(), nullable=True),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('presupuesto_id', sa.Integer(), nullable=True),
    sa.Column('fecha_firma', sa.Date(), nullable=False),
    sa.Column('fecha_inicio', sa.Date(), nullable=True),
    sa.Column('fecha_finalizacion_estimada', sa.Date(), nullable=True),
    sa.Column('estado', sa.String(length=30), nullable=False),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.Column('tipo_cobro', sa.String(length=30), nullable=False),
    sa.Column('moneda', sa.String(length=3), nullable=False),
    sa.Column('aplica_itbis', sa.Boolean(), nullable=False),
    sa.Column('porcentaje_itbis', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('subtotal', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('itbis', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('total_contrato', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('porcentaje_honorario_exito', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('monto_honorario_exito', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('requiere_anticipo', sa.Boolean(), nullable=False),
    sa.Column('monto_anticipo', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['expediente_id'], ['expedientes.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['presupuesto_id'], ['presupuestos.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cronogramas_cobro',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('contrato_id', sa.Integer(), nullable=False),
    sa.Column('descripcion', sa.String(length=255), nullable=False),
    sa.Column('fecha_vencimiento', sa.Date(), nullable=False),
    sa.Column('monto', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('estado', sa.String(length=30), nullable=False),
    sa.Column('orden', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(length=30), nullable=False),
    sa.ForeignKeyConstraint(['contrato_id'], ['contratos_honorarios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('gastos_reembolsables',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('expediente_id', sa.Integer(), nullable=False),
    sa.Column('tipo_gasto', sa.String(length=50), nullable=False),
    sa.Column('descripcion', sa.String(length=255), nullable=False),
    sa.Column('monto', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('estado', sa.String(length=30), nullable=False),
    sa.Column('factura_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['expediente_id'], ['expedientes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['factura_id'], ['facturas_honorarios.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('transacciones_pagos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('factura_id', sa.Integer(), nullable=False),
    sa.Column('recibo_id', sa.Integer(), nullable=True),
    sa.Column('monto', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('fecha_pago', sa.DateTime(timezone=True), nullable=False),
    sa.Column('metodo_pago', sa.String(length=50), nullable=False),
    sa.Column('referencia', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['factura_id'], ['facturas_honorarios.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['recibo_id'], ['recibos_internos.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('facturas_honorarios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('contrato_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('cuota_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'contratos_honorarios', ['contrato_id'], ['id'], ondelete='SET NULL')
        batch_op.create_foreign_key(None, 'cronogramas_cobro', ['cuota_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('presupuestos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('estado', sa.String(length=30), server_default='Borrador', nullable=False))

    with op.batch_alter_table('procedimientos_legales', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tipo_cobro_sugerido', sa.String(length=30), nullable=True))

    # 1. Insertar parámetro fiscal ITBIS por defecto
    op.execute(
        "INSERT INTO parametros_fiscales (clave, valor, descripcion) VALUES ('itbis_default', 18.00, 'Tasa de ITBIS estándar para servicios jurídicos')"
    )

    # 2. Inicializar contratos de honorarios para expedientes existentes
    op.execute(
        """
        INSERT INTO contratos_honorarios (
            expediente_id, cliente_id, fecha_firma, estado, tipo_cobro, moneda, aplica_itbis, porcentaje_itbis, subtotal, itbis, total_contrato, requiere_anticipo
        )
        SELECT 
            id, 
            cliente_id, 
            COALESCE(fecha_contratacion, CURRENT_DATE), 
            'Vigente', 
            COALESCE(esquema_cobro, 'Fijo'), 
            'DOP', 
            TRUE, 
            18.00, 
            COALESCE(tarifa_monto, 0.00), 
            COALESCE(tarifa_monto, 0.00) * 0.18, 
            COALESCE(tarifa_monto, 0.00) * 1.18, 
            FALSE 
        FROM expedientes
        """
    )

    # 3. Vincular facturas existentes al contrato recién creado
    op.execute(
        """
        UPDATE facturas_honorarios f
        SET contrato_id = c.id
        FROM contratos_honorarios c
        WHERE f.expediente_id = c.expediente_id
        """
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('procedimientos_legales', schema=None) as batch_op:
        batch_op.drop_column('tipo_cobro_sugerido')

    with op.batch_alter_table('expedientes', schema=None) as batch_op:
        batch_op.drop_column('porcentaje_exito')
        batch_op.drop_column('tarifa_monto')
        batch_op.drop_column('esquema_cobro')

    with op.batch_alter_table('presupuestos', schema=None) as batch_op:
        batch_op.drop_column('estado')

    with op.batch_alter_table('facturas_honorarios', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('cuota_id')
        batch_op.drop_column('contrato_id')

    op.drop_table('transacciones_pagos')
    op.drop_table('gastos_reembolsables')
    op.drop_table('cronogramas_cobro')
    op.drop_table('contratos_honorarios')
    op.drop_table('recibos_internos')
    op.drop_table('parametros_fiscales')
    op.drop_table('detalles_presupuestos')
    op.drop_table('presupuestos')
    # ### end Alembic commands ###
