"""add_billing_tranches_and_details

Revision ID: 89b95db3f176
Revises: 75cadc9c150a
Create Date: 2026-07-27 13:54:09.011528

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '89b95db3f176'
down_revision = '75cadc9c150a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('detalles_facturas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('factura_id', sa.Integer(), nullable=False),
    sa.Column('descripcion', sa.String(length=255), nullable=False),
    sa.Column('cantidad', sa.Integer(), nullable=False),
    sa.Column('precio_unitario', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('subtotal', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['factura_id'], ['facturas_honorarios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('partidas_pagos_facturas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('factura_id', sa.Integer(), nullable=False),
    sa.Column('descripcion_partida', sa.String(length=255), nullable=False),
    sa.Column('monto', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('fecha_vencimiento', sa.Date(), nullable=False),
    sa.Column('estado_pago', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['factura_id'], ['facturas_honorarios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('facturas_honorarios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('expediente_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'expedientes', ['expediente_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('registros_envios_alertas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('partida_factura_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'partidas_pagos_facturas', ['partida_factura_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('registros_envios_alertas', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('partida_factura_id')

    with op.batch_alter_table('facturas_honorarios', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('expediente_id')

    op.drop_table('partidas_pagos_facturas')
    op.drop_table('detalles_facturas')
    # ### end Alembic commands ###
