"""add_requiere_procedimiento_to_materia

Revision ID: 8fc5d1f84bca
Revises: 4a256ecec8c1
Create Date: 2026-07-27 23:29:25.163362

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8fc5d1f84bca'
down_revision = '4a256ecec8c1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('materias_legales', schema=None) as batch_op:
        batch_op.add_column(sa.Column('requiere_procedimiento', sa.Boolean(), server_default='true', nullable=False))

    # Establecer requiere_procedimiento = False para las materias específicas
    op.execute(
        "UPDATE materias_legales SET requiere_procedimiento = FALSE WHERE nombre IN ('Ayuntamientos', 'JCE', 'Ministerio de Trabajo')"
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('materias_legales', schema=None) as batch_op:
        batch_op.drop_column('requiere_procedimiento')

    # ### end Alembic commands ###
