"""add_cierre_and_fases_to_expediente

Revision ID: b4706b9ca634
Revises: 31aa40d60215
Create Date: 2026-07-16 12:41:57.285714

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b4706b9ca634'
down_revision = '31aa40d60215'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('expedientes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tipo_finalizacion', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('fase_actual', sa.Integer(), server_default='1', nullable=False))
        batch_op.add_column(sa.Column('fase_nota', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('expedientes', schema=None) as batch_op:
        batch_op.drop_column('fase_nota')
        batch_op.drop_column('fase_actual')
        batch_op.drop_column('tipo_finalizacion')

    # ### end Alembic commands ###
