"""Creacion inicial de las tablas

Revision ID: bbe567fa86a7
Revises: 
Create Date: 2026-06-23 20:46:53.751638

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bbe567fa86a7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tipos_documentos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre_tipo', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre_tipo')
    )
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('rol', sa.String(length=50), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('requiere_cambio_password', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('clientes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rnc_cedula', sa.String(length=11), nullable=False),
    sa.Column('nombre', sa.String(length=255), nullable=False),
    sa.Column('telefono', sa.String(length=20), nullable=True),
    sa.Column('email_contacto', sa.String(length=150), nullable=False),
    sa.Column('consentimiento_datos', sa.Boolean(), nullable=False),
    sa.Column('fecha_consentimiento', sa.DateTime(timezone=True), nullable=True),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('rnc_cedula')
    )
    op.create_table('expedientes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo_firma', sa.String(length=50), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('nombre_caso', sa.String(length=255), nullable=False),
    sa.Column('tipo_tramite', sa.String(length=50), nullable=False),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.Column('fecha_apertura', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo_firma')
    )
    op.create_table('facturas_honorarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('ncf', sa.String(length=13), nullable=True),
    sa.Column('tipo_comprobante', sa.String(length=2), nullable=False),
    sa.Column('monto_subtotal', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('monto_itbis', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('monto_total', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('fecha_emision', sa.DateTime(timezone=True), nullable=False),
    sa.Column('estado_pago', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ncf')
    )
    op.create_table('alertas_plazos_audiencias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('expediente_id', sa.Integer(), nullable=False),
    sa.Column('titulo_hito', sa.String(length=255), nullable=False),
    sa.Column('fecha_vencimiento', sa.DateTime(timezone=True), nullable=False),
    sa.Column('estado_alerta', sa.String(length=20), nullable=False),
    sa.Column('fuente_origen', sa.String(length=30), nullable=False),
    sa.ForeignKeyConstraint(['expediente_id'], ['expedientes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bitacora_auditoria',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('fecha_hora', sa.DateTime(timezone=True), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('expediente_id', sa.Integer(), nullable=True),
    sa.Column('accion_realizada', sa.String(length=50), nullable=False),
    sa.Column('detalles_tecnicos', sa.Text(), nullable=False),
    sa.Column('ip_direccion', sa.String(length=45), nullable=False),
    sa.Column('dispositivo_info', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['expediente_id'], ['expedientes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bitacora_tiempos_tareas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('expediente_id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('fecha_tarea', sa.Date(), nullable=False),
    sa.Column('horas_trabajadas', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('descripcion_gestion', sa.Text(), nullable=False),
    sa.Column('estado_cierre', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['expediente_id'], ['expedientes.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('documentos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('expediente_id', sa.Integer(), nullable=False),
    sa.Column('tipo_documento_id', sa.Integer(), nullable=False),
    sa.Column('visibilidad', sa.String(length=30), nullable=False),
    sa.ForeignKeyConstraint(['expediente_id'], ['expedientes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tipo_documento_id'], ['tipos_documentos.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('versiones_documentos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('documento_id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('version_numero', sa.String(length=10), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('fecha_carga', sa.DateTime(timezone=True), nullable=False),
    sa.Column('tamano_bytes', sa.BigInteger(), nullable=False),
    sa.Column('ruta_almacenamiento', sa.String(length=500), nullable=False),
    sa.Column('es_firmado', sa.Boolean(), nullable=False),
    sa.Column('hash_firma', sa.String(length=512), nullable=True),
    sa.ForeignKeyConstraint(['documento_id'], ['documentos.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('versiones_documentos')
    op.drop_table('documentos')
    op.drop_table('bitacora_tiempos_tareas')
    op.drop_table('bitacora_auditoria')
    op.drop_table('alertas_plazos_audiencias')
    op.drop_table('facturas_honorarios')
    op.drop_table('expedientes')
    op.drop_table('clientes')
    op.drop_table('usuarios')
    op.drop_table('tipos_documentos')
    # ### end Alembic commands ###
