"""make_task_assigned_to_nullable

Revision ID: bc732920df5c
Revises: f0e758c951b8
Create Date: 2026-07-09 23:51:45.570543

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bc732920df5c'
down_revision = 'f0e758c951b8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tareas', schema=None) as batch_op:
        batch_op.alter_column('asignado_a_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tareas', schema=None) as batch_op:
        batch_op.alter_column('asignado_a_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
