"""add razon_estado to expediente

Revision ID: bceea8685c59
Revises: 16fbab9ed93f
Create Date: 2026-07-08 20:53:28.725627

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bceea8685c59'
down_revision = '16fbab9ed93f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('expedientes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('razon_estado', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('expedientes', schema=None) as batch_op:
        batch_op.drop_column('razon_estado')

    # ### end Alembic commands ###
