"""add_payment_terms_mora_and_pdf

Revision ID: cae851fe6c86
Revises: 89b95db3f176
Create Date: 2026-07-27 14:03:16.492918

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cae851fe6c86'
down_revision = '89b95db3f176'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('facturas_honorarios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('plazo_pago_dias', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('tasa_mora_mensual', sa.Numeric(precision=5, scale=2), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('facturas_honorarios', schema=None) as batch_op:
        batch_op.drop_column('tasa_mora_mensual')
        batch_op.drop_column('plazo_pago_dias')

    # ### end Alembic commands ###
