"""add_notificaciones_internas_and_registro_envio_alerta

Revision ID: ce678d08da91
Revises: 31aa40d60215
Create Date: 2026-07-16 11:40:13.113795

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ce678d08da91'
down_revision = '31aa40d60215'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notificaciones_internas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('mensaje', sa.String(length=500), nullable=False),
    sa.Column('leida', sa.Boolean(), nullable=False),
    sa.Column('fecha_creacion', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expediente_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['expediente_id'], ['expedientes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('registros_envios_alertas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('alerta_id', sa.Integer(), nullable=True),
    sa.Column('tarea_id', sa.Integer(), nullable=True),
    sa.Column('dias_anticipacion', sa.Integer(), nullable=False),
    sa.Column('fecha_envio', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['alerta_id'], ['alertas_plazos_audiencias.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tarea_id'], ['tareas.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('registros_envios_alertas')
    op.drop_table('notificaciones_internas')
    # ### end Alembic commands ###
