"""add_fields_to_user_model

Revision ID: d5c8a5b18b96
Revises: 44f839aa0701
Create Date: 2026-07-30 12:10:13.627227

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd5c8a5b18b96'
down_revision = '44f839aa0701'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cedula', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('fecha_nacimiento', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('telefono', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('direccion', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.drop_column('direccion')
        batch_op.drop_column('telefono')
        batch_op.drop_column('fecha_nacimiento')
        batch_op.drop_column('cedula')

    # ### end Alembic commands ###
