"""Add carpetas model

Revision ID: df1b11be1d82
Revises: bceea8685c59
Create Date: 2026-07-09 01:56:09.826932

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'df1b11be1d82'
down_revision = 'bceea8685c59'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('carpetas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('expediente_id', sa.Integer(), nullable=False),
    sa.Column('fecha_creacion', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['expediente_id'], ['expedientes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('documentos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('carpeta_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'carpetas', ['carpeta_id'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('documentos', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('carpeta_id')

    op.drop_table('carpetas')
    # ### end Alembic commands ###
