"""add_expediente_abogados_relation

Revision ID: df280d437929
Revises: e993f3b55541
Create Date: 2026-07-28 10:27:10.267809

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'df280d437929'
down_revision = 'e993f3b55541'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('expediente_abogados',
    sa.Column('expediente_id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['expediente_id'], ['expedientes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('expediente_id', 'usuario_id')
    )
    # Migración de datos históricos: poblar expediente_abogados con el abogado responsable actual
    op.execute(
        """
        INSERT INTO expediente_abogados (expediente_id, usuario_id)
        SELECT id, abogado_responsable_id 
        FROM expedientes 
        WHERE abogado_responsable_id IS NOT NULL
        """
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('expediente_abogados')
    # ### end Alembic commands ###
