"""simplify_billing_model

Revision ID: e72ee38ebb54
Revises: d5c8a5b18b96
Create Date: 2026-08-01 00:07:39.254444

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e72ee38ebb54'
down_revision = 'd5c8a5b18b96'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('registros_envios_alertas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('factura_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint('registros_envios_alertas_partida_factura_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'facturas_honorarios', ['factura_id'], ['id'], ondelete='CASCADE')
        batch_op.drop_column('partida_factura_id')

    op.drop_table('partidas_pagos_facturas')

    with op.batch_alter_table('facturas_honorarios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fecha_vencimiento', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('registros_envios_alertas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('partida_factura_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('registros_envios_alertas_partida_factura_id_fkey'), 'partidas_pagos_facturas', ['partida_factura_id'], ['id'], ondelete='CASCADE')
        batch_op.drop_column('factura_id')

    with op.batch_alter_table('facturas_honorarios', schema=None) as batch_op:
        batch_op.drop_column('fecha_vencimiento')

    op.create_table('partidas_pagos_facturas',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('factura_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('descripcion_partida', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('monto', sa.NUMERIC(precision=18, scale=2), autoincrement=False, nullable=False),
    sa.Column('fecha_vencimiento', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('estado_pago', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['factura_id'], ['facturas_honorarios.id'], name=op.f('partidas_pagos_facturas_factura_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('partidas_pagos_facturas_pkey'))
    )
    # ### end Alembic commands ###
