"""detect_changes

Revision ID: e993f3b55541
Revises: 793927c103c1
Create Date: 2026-07-28 09:56:55.171983

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e993f3b55541'
down_revision = '793927c103c1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('salario_base', sa.Numeric(precision=18, scale=2), nullable=True))
        batch_op.add_column(sa.Column('porcentaje_comision', sa.Numeric(precision=5, scale=2), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.drop_column('porcentaje_comision')
        batch_op.drop_column('salario_base')

    # ### end Alembic commands ###
