"""detect_changes

Revision ID: e993f3b55541
Revises: 793927c103c1
Create Date: 2026-07-28 09:56:55.171983

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e993f3b55541'
down_revision = '793927c103c1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    columns = [col['name'] for col in inspector.get_columns('usuarios')]
    
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        if 'salario_base' not in columns:
            batch_op.add_column(sa.Column('salario_base', sa.Numeric(precision=18, scale=2), nullable=True))
        if 'porcentaje_comision' not in columns:
            batch_op.add_column(sa.Column('porcentaje_comision', sa.Numeric(precision=5, scale=2), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    columns = [col['name'] for col in inspector.get_columns('usuarios')]

    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        if 'porcentaje_comision' in columns:
            batch_op.drop_column('porcentaje_comision')
        if 'salario_base' in columns:
            batch_op.drop_column('salario_base')

    # ### end Alembic commands ###
