"""refactor: nuevos campos para los modelos

Revision ID: eaf00d09fc4c
Revises: 5c14fe94c45e
Create Date: 2026-06-30 20:34:11.506225

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eaf00d09fc4c'
down_revision = '5c14fe94c45e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('expedientes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('abogado_responsable_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('rol_firma', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('fecha_cierre', sa.DateTime(timezone=True), nullable=True))
        batch_op.create_foreign_key(None, 'usuarios', ['abogado_responsable_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('expedientes_administrativos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('numero_solicitud_oficial', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('monto_tasas_impuestos', sa.Numeric(precision=12, scale=2), nullable=True))

    with op.batch_alter_table('expedientes_judiciales', schema=None) as batch_op:
        batch_op.add_column(sa.Column('jurisdiccion_actual', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('nombre_contraparte', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('contacto_contraparte', sa.String(length=150), nullable=True))
        batch_op.add_column(sa.Column('abogado_contraparte', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('contacto_abogado_contraparte', sa.String(length=150), nullable=True))
        batch_op.add_column(sa.Column('monto_demanda', sa.Numeric(precision=15, scale=2), nullable=True))

    with op.batch_alter_table('requisitos_administrativos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('requiere_legalizacion', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('requiere_apostilla', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('requiere_traduccion', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('requisitos_administrativos', schema=None) as batch_op:
        batch_op.drop_column('requiere_traduccion')
        batch_op.drop_column('requiere_apostilla')
        batch_op.drop_column('requiere_legalizacion')

    with op.batch_alter_table('expedientes_judiciales', schema=None) as batch_op:
        batch_op.drop_column('monto_demanda')
        batch_op.drop_column('contacto_abogado_contraparte')
        batch_op.drop_column('abogado_contraparte')
        batch_op.drop_column('contacto_contraparte')
        batch_op.drop_column('nombre_contraparte')
        batch_op.drop_column('jurisdiccion_actual')

    with op.batch_alter_table('expedientes_administrativos', schema=None) as batch_op:
        batch_op.drop_column('monto_tasas_impuestos')
        batch_op.drop_column('numero_solicitud_oficial')

    with op.batch_alter_table('expedientes', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('fecha_cierre')
        batch_op.drop_column('rol_firma')
        batch_op.drop_column('abogado_responsable_id')

    # ### end Alembic commands ###
