"""make_expediente_mandatory_in_tasks

Revision ID: f0e758c951b8
Revises: bd28a8aaee49
Create Date: 2026-07-09 23:21:53.323867

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f0e758c951b8'
down_revision = 'bd28a8aaee49'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tareas', schema=None) as batch_op:
        batch_op.alter_column('expediente_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_constraint(batch_op.f('tareas_expediente_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'expedientes', ['expediente_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tareas', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('tareas_expediente_id_fkey'), 'expedientes', ['expediente_id'], ['id'], ondelete='SET NULL')
        batch_op.alter_column('expediente_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
